
package com.foya.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-05-29T11:40:39.525+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class MyService_MyServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.madbit.org/MyService/", "MyService");

    private MyService_MyServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MyService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MyService_Service ss = new MyService_Service(wsdlURL, SERVICE_NAME);
        MyService port = ss.getMyServiceSOAP();  
        
        {
        System.out.println("Invoking sum...");
        com.foya.client.SumRequest _sum_parameters = null;
        com.foya.client.SumResponse _sum__return = port.sum(_sum_parameters);
        System.out.println("sum.result=" + _sum__return);


        }

        System.exit(0);
    }

}
