<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    targetNamespace="http://benchresources.in/services/BookService/"
    xmlns:tns="http://benchresources.in/services/BookService/" xmlns:book="http://benchresources.in/entities/Book"
    name="BookService">

    <wsdl:types>
        <xsd:schema targetNamespace="http://benchresources.in/services/BookService/">
            <xsd:import namespace="http://benchresources.in/entities/Book"
                schemaLocation="book.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="BookRequest">
        <wsdl:part element="book:BookRequestType" name="parameters" />
    </wsdl:message>
    <wsdl:message name="BookResponse">
        <wsdl:part element="book:BookResponseType" name="parameters" />
    </wsdl:message>

    <wsdl:portType name="IBookService">
        <wsdl:operation name="getBookByISDNRequestNumber">
            <wsdl:input message="tns:BookRequest" />
            <wsdl:output message="tns:BookResponse" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="BookServiceSOAPBinding" type="tns:IBookService">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="getBookByISDNRequestNumber">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="BookService">
        <wsdl:port name="BookServicePort" binding="tns:BookServiceSOAPBinding">
            <soap:address
                location="http://localhost:8080/ApacheCXF-JAX-WS-Top-Down/services/book/BookService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>