package com.foya.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-05-29T11:41:55.152+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.madbit.org/MyService/", name = "MyService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MyService {

    @WebResult(name = "SumResponse", targetNamespace = "http://www.madbit.org/MyService/", partName = "parameters")
    @WebMethod(operationName = "Sum", action = "http://www.madbit.org/MyService/Sum")
    public SumResponse sum(
        @WebParam(partName = "parameters", name = "SumRequest", targetNamespace = "http://www.madbit.org/MyService/")
        SumRequest parameters
    );
}
