
package com.foya.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-05-29T11:41:55.161+08:00
 * Generated source version: 3.1.2
 * 
 */
 
public class MyService_MyServiceSOAP_Server{

    protected MyService_MyServiceSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MyServiceSOAPImpl();
        String address = "http://www.madbit.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new MyService_MyServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
