
package com.foya.demo03.client.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://server.demo03.foya.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server.demo03.foya.com/", className = "com.foya.demo03.client.wsimport.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.demo03.foya.com/", className = "com.foya.demo03.client.wsimport.AddResponse")
    @Action(input = "http://server.demo03.foya.com/IMyService/addRequest", output = "http://server.demo03.foya.com/IMyService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://server.demo03.foya.com/", className = "com.foya.demo03.client.wsimport.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://server.demo03.foya.com/", className = "com.foya.demo03.client.wsimport.MinusResponse")
    @Action(input = "http://server.demo03.foya.com/IMyService/minusRequest", output = "http://server.demo03.foya.com/IMyService/minusResponse")
    public int minus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.foya.demo03.client.wsimport.User
     */
    @WebMethod
    @WebResult(name = "loginUser", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://server.demo03.foya.com/", className = "com.foya.demo03.client.wsimport.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://server.demo03.foya.com/", className = "com.foya.demo03.client.wsimport.LoginResponse")
    @Action(input = "http://server.demo03.foya.com/IMyService/loginRequest", output = "http://server.demo03.foya.com/IMyService/loginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
