package com.foya.all;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-05-29T11:40:28.679+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "MyService", 
                  wsdlLocation = "file:MyService.wsdl",
                  targetNamespace = "http://www.madbit.org/MyService/") 
public class MyService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.madbit.org/MyService/", "MyService");
    public final static QName MyServiceSOAP = new QName("http://www.madbit.org/MyService/", "MyServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:MyService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:MyService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MyService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceSOAP")
    public MyService getMyServiceSOAP() {
        return super.getPort(MyServiceSOAP, MyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceSOAP")
    public MyService getMyServiceSOAP(WebServiceFeature... features) {
        return super.getPort(MyServiceSOAP, MyService.class, features);
    }

}
