
package com.foya.demo02.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://server.demo02.foya.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server.demo02.foya.com/", className = "com.foya.demo02.server.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.demo02.foya.com/", className = "com.foya.demo02.server.AddResponse")
    @Action(input = "http://server.demo02.foya.com/IMyService/addRequest", output = "http://server.demo02.foya.com/IMyService/addResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "minusResult", targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://server.demo02.foya.com/", className = "com.foya.demo02.server.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://server.demo02.foya.com/", className = "com.foya.demo02.server.MinusResponse")
    @Action(input = "http://server.demo02.foya.com/IMyService/minusRequest", output = "http://server.demo02.foya.com/IMyService/minusResponse")
    public int minus(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
